services:
  backend:
    init: false
    entrypoint: ["node", "--inspect=0.0.0.0:9229", "--watch", "src/server.js"]
    ports:
      - "127.0.0.1:9229:9229"
    security_opt: !reset []
    cap_drop: !reset []
    read_only: false
    volumes:
      - ./backend/src:/app/src

  oxide_control_panel:
    init: false
    security_opt: !reset []
    cap_drop: !reset []
    read_only: false

  oxide_web:
    security_opt: !reset []
    cap_drop: !reset []
    read_only: false

  postgres:
    ports: !reset []

  worker-deployments:
    init: false
    entrypoint: ["node", "--watch", "src/worker.js"]
    security_opt: !reset []
    cap_drop: !reset []
    read_only: false

  worker-stats:
    init: false
    entrypoint: ["node", "--watch", "src/worker.js"]
    security_opt: !reset []
    cap_drop: !reset []
    read_only: false