import fs from 'fs/promises';
import { JSDOM } from 'jsdom';

const htmlFiles = [
  'frontend/public/index.html',
  'frontend/public/hosting-fivem.html',
  'frontend/public/creadores.html'
];
const manifestPath = 'scripts/security/public-inline-handler-manifest.json';
const outputPath = 'frontend/public/js/public-actions.generated.js';

let manifest = { version: 1, handlers: [] };
try {
  manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}

const bySource = new Map(
  manifest.handlers.map(handler => [`${handler.event}\u0000${handler.source}`, handler])
);
let nextId = manifest.handlers.reduce((max, handler) => {
  const numeric = Number(String(handler.id).replace(/^pub_/, ''));
  return Number.isFinite(numeric) ? Math.max(max, numeric + 1) : max;
}, 1);
let migrated = 0;

for (const file of htmlFiles) {
  let source = await fs.readFile(file, 'utf8');
  const dom = new JSDOM(source, { includeNodeLocations: true });
  const edits = [];

  for (const element of dom.window.document.querySelectorAll('*')) {
    const location = dom.nodeLocation(element);
    if (!location?.attrs) continue;
    for (const attribute of [...element.attributes]) {
      if (!/^on[a-z]+$/i.test(attribute.name)) continue;
      const attributeLocation = location.attrs[attribute.name];
      if (!attributeLocation) throw new Error(`Missing source location for ${attribute.name} in ${file}`);

      const event = attribute.name.slice(2).toLowerCase();
      const key = `${event}\u0000${attribute.value}`;
      let handler = bySource.get(key);
      if (!handler) {
        handler = {
          id: `pub_${String(nextId++).padStart(4, '0')}`,
          event,
          source: attribute.value
        };
        manifest.handlers.push(handler);
        bySource.set(key, handler);
      }

      edits.push({
        start: attributeLocation.startOffset,
        end: attributeLocation.endOffset,
        replacement: `data-rn-on${event}="${handler.id}"`
      });
      migrated += 1;
    }
  }

  for (const edit of edits.sort((a, b) => b.start - a.start)) {
    source = source.slice(0, edit.start) + edit.replacement + source.slice(edit.end);
  }
  if (edits.length) await fs.writeFile(file, source);
}

manifest.handlers.sort((a, b) => a.id.localeCompare(b.id));
await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

const handlerEntries = manifest.handlers.map(handler => {
  const body = handler.source.split('\n').map(line => `      ${line}`).join('\n');
  return `    ${JSON.stringify(handler.id)}: function (event) {\n${body}\n    }`;
}).join(',\n');
const eventTypes = [...new Set([...manifest.handlers.map(handler => handler.event), 'click'])].sort();

const generated = `'use strict';

// Generated by scripts/security/migrate_public_handlers.mjs.
// Inline event attributes are compiled into this same-origin script so the
// public pages can enforce script-src-attr 'none'.
(() => {
  const handlers = Object.freeze({
${handlerEntries}
  });

  const dynamicActions = Object.freeze({
    'open-checkout': function (event, element) {
      const encodedPlanId = element.getAttribute('data-rn-plan-id') || '';
      globalThis.openCheckout(decodeURIComponent(encodedPlanId));
    },
    'open-checkout-stop': function (event, element) {
      event.stopPropagation();
      const encodedPlanId = element.getAttribute('data-rn-plan-id') || '';
      globalThis.openCheckout(decodeURIComponent(encodedPlanId));
    }
  });

  function invoke(element, event, eventType) {
    if (eventType === 'click') {
      const actionName = element.getAttribute('data-rn-action');
      if (actionName) {
        const action = dynamicActions[actionName];
        if (!action) throw new Error('Unknown public action: ' + actionName);
        return action.call(element, event, element);
      }
    }

    const handlerId = element.getAttribute('data-rn-on' + eventType);
    if (!handlerId) return undefined;
    const handler = handlers[handlerId];
    if (!handler) throw new Error('Unknown public handler: ' + handlerId);
    return handler.call(element, event);
  }

  function dispatch(event) {
    for (const target of event.composedPath()) {
      if (!(target instanceof Element)) continue;
      try {
        if (invoke(target, event, event.type) === false) event.preventDefault();
      } catch (error) {
        console.error('[PublicAction]', error);
      }
      if (event.cancelBubble) break;
    }
  }

  for (const eventType of ${JSON.stringify(eventTypes)}) {
    document.addEventListener(eventType, dispatch, eventType === 'focus' || eventType === 'blur');
  }
})();
`;

await fs.writeFile(outputPath, generated);

for (const file of htmlFiles) {
  const source = await fs.readFile(file, 'utf8');
  const dom = new JSDOM(source);
  const inlineHandlers = [...dom.window.document.querySelectorAll('*')]
    .flatMap(element => [...element.attributes])
    .filter(attribute => /^on[a-z]+$/i.test(attribute.name));
  if (inlineHandlers.length) throw new Error(`${file} still has ${inlineHandlers.length} inline handlers`);

  for (const element of dom.window.document.querySelectorAll('*')) {
    for (const attribute of [...element.attributes]) {
      const match = attribute.name.match(/^data-rn-on([a-z]+)$/);
      if (!match) continue;
      const handler = manifest.handlers.find(item => item.id === attribute.value);
      if (!handler || handler.event !== match[1]) {
        throw new Error(`Invalid handler mapping ${attribute.value} in ${file}`);
      }
    }
  }
}

console.log(`Migrated ${migrated} public inline handlers; ${manifest.handlers.length} unique handlers compiled.`);
