import fs from 'fs/promises';
import { JSDOM } from 'jsdom';

const htmlFiles = [
  'frontend/public/admin.html',
  'frontend/public/panel.html',
  'frontend/public/games/ark.html',
  'frontend/public/games/cs2.html',
  'frontend/public/games/database.html',
  'frontend/public/games/discordbot.html',
  'frontend/public/games/fivem.html',
  'frontend/public/games/fivem_v3.html',
  'frontend/public/games/minecraft.html',
  'frontend/public/games/palworld.html',
  'frontend/public/games/rust.html',
  'frontend/public/games/sdtd.html',
  'frontend/public/games/valheim.html',
  'frontend/public/games/wordpress.html',
  'frontend/public/games/zomboid.html'
];
const manifestPath = 'scripts/security/privileged-inline-handler-manifest.json';
const outputPath = 'frontend/public/js/privileged-actions.generated.js';

let manifest = { version: 1, handlers: [] };
try {
  manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}

const bySource = new Map(
  manifest.handlers.map((handler) => [`${handler.event}\u0000${handler.source}`, handler])
);
let nextId = manifest.handlers.reduce((max, handler) => {
  const numeric = Number(String(handler.id).replace(/^priv_/, ''));
  return Number.isFinite(numeric) ? Math.max(max, numeric + 1) : max;
}, 1);
let migrated = 0;

function allElements(root) {
  const elements = [...root.querySelectorAll('*')];
  for (const element of [...elements]) {
    if (element.tagName === 'TEMPLATE') elements.push(...allElements(element.content));
  }
  return elements;
}

for (const file of htmlFiles) {
  let source = await fs.readFile(file, 'utf8');
  const dom = new JSDOM(source, { includeNodeLocations: true });
  const edits = [];

  for (const element of allElements(dom.window.document)) {
    const location = dom.nodeLocation(element);
    if (!location?.attrs) continue;
    for (const attribute of [...element.attributes]) {
      if (!/^on[a-z]+$/i.test(attribute.name)) continue;
      const attributeLocation = location.attrs[attribute.name];
      if (!attributeLocation) throw new Error(`Missing source location for ${attribute.name} in ${file}`);

      const event = attribute.name.slice(2).toLowerCase();
      const key = `${event}\u0000${attribute.value}`;
      let handler = bySource.get(key);
      if (!handler) {
        handler = {
          id: `priv_${String(nextId++).padStart(4, '0')}`,
          event,
          source: attribute.value
        };
        manifest.handlers.push(handler);
        bySource.set(key, handler);
      }

      edits.push({
        start: attributeLocation.startOffset,
        end: attributeLocation.endOffset,
        replacement: `data-rn-on${event}="${handler.id}"`
      });
      migrated += 1;
    }
  }

  for (const edit of edits.sort((a, b) => b.start - a.start)) {
    source = source.slice(0, edit.start) + edit.replacement + source.slice(edit.end);
  }
  if (edits.length) await fs.writeFile(file, source);
}

manifest.handlers.sort((a, b) => a.id.localeCompare(b.id));
await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

const handlerEntries = manifest.handlers.map((handler) => {
  const body = handler.source.split('\n').map((line) => `      ${line}`).join('\n');
  return `    ${JSON.stringify(handler.id)}: function (event) {\n${body}\n    }`;
}).join(',\n');
const eventTypes = [...new Set(manifest.handlers.map((handler) => handler.event))].sort();

const generated = `'use strict';

// Generated by scripts/security/migrate_privileged_handlers.mjs.
// Fixed admin and panel controls are delegated so privileged pages can move
// away from executable HTML attributes without eval or unsafe-eval.
(() => {
  const handlers = Object.freeze({
${handlerEntries}
  });

  function dispatch(event) {
    for (const target of event.composedPath()) {
      if (!(target instanceof Element)) continue;
      const handlerId = target.getAttribute('data-rn-on' + event.type);
      if (!handlerId) continue;
      const handler = handlers[handlerId];
      if (!handler) {
        console.error('[PrivilegedAction] Unknown handler:', handlerId);
        continue;
      }
      try {
        if (handler.call(target, event) === false) event.preventDefault();
      } catch (error) {
        console.error('[PrivilegedAction]', error);
      }
      if (event.cancelBubble) break;
    }
  }

  for (const eventType of ${JSON.stringify(eventTypes)}) {
    document.addEventListener(eventType, dispatch, eventType === 'focus' || eventType === 'blur');
  }
})();
`;

await fs.writeFile(outputPath, generated);

for (const file of htmlFiles) {
  const source = await fs.readFile(file, 'utf8');
  const document = new JSDOM(source).window.document;
  const inlineHandlers = allElements(document)
    .flatMap((element) => [...element.attributes])
    .filter((attribute) => /^on[a-z]+$/i.test(attribute.name));
  if (inlineHandlers.length) throw new Error(`${file} still has ${inlineHandlers.length} inline handlers`);

  for (const element of allElements(document)) {
    for (const attribute of [...element.attributes]) {
      const match = attribute.name.match(/^data-rn-on([a-z]+)$/);
      if (!match) continue;
      const handler = manifest.handlers.find((item) => item.id === attribute.value);
      if (!handler || handler.event !== match[1]) {
        throw new Error(`Invalid handler mapping ${attribute.value} in ${file}`);
      }
    }
  }
}

console.log(`Migrated ${migrated} privileged inline handlers; ${manifest.handlers.length} unique handlers compiled.`);
