#!/bin/sh
set -eu

manifest_file="${1:-registry-release.env}"
lock_file="deploy/registry-release.lock"

: "${GITLAB_TOKEN:?GITLAB_TOKEN must be configured as a masked protected CI variable}"
: "${CI_SERVER_HOST:?Missing CI_SERVER_HOST}"
: "${CI_PROJECT_PATH:?Missing CI_PROJECT_PATH}"
: "${CI_COMMIT_SHA:?Missing CI_COMMIT_SHA}"
: "${CI_COMMIT_SHORT_SHA:?Missing CI_COMMIT_SHORT_SHA}"

[ "${CI_COMMIT_BRANCH:-}" = "dev" ] || {
  echo "Automatic release manifests are created only from dev."
  exit 0
}
[ -f "$manifest_file" ] || { echo "ERROR: missing $manifest_file" >&2; exit 2; }

validate_manifest() {
  revision_count="$(grep -Ec '^RAGENODES_RELEASE_REVISION=[0-9a-f]{40}$' "$manifest_file" || true)"
  [ "$revision_count" -eq 1 ] || { echo "ERROR: manifest needs one valid release revision." >&2; return 1; }
  grep -Fx "RAGENODES_RELEASE_REVISION=$CI_COMMIT_SHA" "$manifest_file" >/dev/null || {
    echo "ERROR: manifest revision does not match the pipeline commit." >&2
    return 1
  }

  for entry in \
    'RAGENODES_BACKEND_IMAGE=backend' \
    'RAGENODES_BOT_IMAGE=bot' \
    'RAGENODES_OXIDEPROXY_IMAGE=oxideproxy' \
    'RAGENODES_OXIDE_CONTROL_PANEL_IMAGE=oxide-control-panel'; do
    variable="${entry%%=*}"
    component="${entry#*=}"
    count="$(grep -Ec "^${variable}=registry\\.gitlab\\.com/mariomatos/ragenodesultimate/${component}@sha256:[0-9a-f]{64}$" "$manifest_file" || true)"
    [ "$count" -eq 1 ] || {
      echo "ERROR: invalid or duplicate immutable reference for $component." >&2
      return 1
    }
  done

  [ "$(wc -l < "$manifest_file" | tr -d ' ')" -eq 5 ] || {
    echo "ERROR: unexpected fields in registry release manifest." >&2
    return 1
  }
}

validate_manifest

if [ -f "$lock_file" ] && grep -Fx "RAGENODES_RELEASE_REVISION=$CI_COMMIT_SHA" "$lock_file" >/dev/null; then
  echo "Release lock already points to $CI_COMMIT_SHA."
  exit 0
fi

release_branch="release/registry-manifest-${CI_COMMIT_SHORT_SHA}"
remote_url="https://oauth2:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"

if git ls-remote --exit-code --heads "$remote_url" "$release_branch" >/dev/null 2>&1; then
  echo "Release branch $release_branch already exists; no duplicate MR created."
  exit 0
fi

git config user.name "RageNodes Release Bot"
git config user.email "release-bot@ragenodes.internal"
git switch -c "$release_branch"
{
  echo '# Generated from a successful dev package pipeline. Promote this file unchanged.'
  cat "$manifest_file"
} > "$lock_file"
git add "$lock_file"
git commit -m "chore(release): registry manifest ${CI_COMMIT_SHORT_SHA}"

git push "$remote_url" "HEAD:$release_branch" \
  -o merge_request.create \
  -o merge_request.target=dev \
  -o merge_request.title="chore(release): promote registry manifest ${CI_COMMIT_SHORT_SHA}" \
  -o merge_request.description="Automated immutable image manifest generated by successful dev pipeline ${CI_PIPELINE_URL:-unknown}. Do not edit digest values manually." \
  -o merge_request.remove_source_branch \
  -o merge_request.merge_when_pipeline_succeeds

echo "Created auto-merge release manifest MR for $CI_COMMIT_SHA."
