import express from 'express';
import fs from 'fs/promises';
import path from 'path';
import { requireAuth } from '../middleware/auth.js';
import { getServerByIdForUser } from '../services/serverService.js';
import { safeWriteFile, safeReadFile } from '../utils/fileUtil.js';

const router = express.Router();

// Helper para parsear .properties a JSON
function parseProperties(content) {
    const props = {};
    if (typeof content !== 'string') return props;
    const lines = content.split('\n');
    lines.forEach(line => {
        line = line.trim();
        if (line && !line.startsWith('#')) {
            const [key, ...valueParts] = line.split('=');
            if (key) {
                props[key.trim()] = valueParts.join('=').trim();
            }
        }
    });
    return props;
}

// Helper para convertir JSON a .properties
function stringifyProperties(props) {
    let content = '# Minecraft server properties\n# Generated by RageNodes\n';
    for (const [key, value] of Object.entries(props)) {
        content += `${key}=${value}\n`;
    }
    return content;
}

// 1. Obtener propiedades del servidor
router.get('/:serverId/properties', requireAuth, async (req, res) => {
    try {
        const { serverId } = req.params;
        const server = await getServerByIdForUser(serverId, req.user.sub, req.user.role === 'admin', 'files');
        
        if (!server || server.template !== 'minecraft') {
            return res.status(403).json({ error: 'Servidor no válido o sin acceso' });
        }

        const propsPath = path.join(server.data_path, 'server.properties');
        let content = '';
        try {
            content = await safeReadFile(propsPath);
        } catch (e) {
            return res.status(404).json({ error: 'Archivo server.properties no encontrado' });
        }

        const props = parseProperties(content);
        res.json(props);
    } catch (error) {
        console.error('Error leyendo propiedades:', error);
        res.status(500).json({ error: 'Error al leer la configuración' });
    }
});

// 2. Guardar propiedades del servidor
router.post('/:serverId/properties', requireAuth, async (req, res) => {
    try {
        const { serverId } = req.params;
        const newProps = req.body;
        const server = await getServerByIdForUser(serverId, req.user.sub, req.user.role === 'admin', 'files');

        if (!server || server.template !== 'minecraft') {
            return res.status(403).json({ error: 'Servidor no válido o sin acceso' });
        }

        const propsPath = path.join(server.data_path, 'server.properties');
        
        // Leemos las actuales para no perder las que no están en el body (opcional, pero más seguro)
        let currentContent = '';
        try { currentContent = await safeReadFile(propsPath); } catch(e){}
        const currentProps = parseProperties(currentContent);

        // Fusionamos
        const finalProps = { ...currentProps, ...newProps };
        const newContent = stringifyProperties(finalProps);

        await safeWriteFile(propsPath, newContent);
        res.json({ success: true, message: 'Configuración guardada correctamente' });
    } catch (error) {
        console.error('Error guardando propiedades:', error);
        res.status(500).json({ error: 'Error al guardar la configuración' });
    }
});

export default router;
