FROM node:20-alpine@sha256:fb4cd12c85ee03686f6af5362a0b0d56d50c58a04632e6c0fb8363f609372293

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev --ignore-scripts

COPY server.js ./
COPY public ./public
RUN mkdir -p /app/rust_config

EXPOSE 3000
CMD ["node", "server.js"]
